### PR TITLE
Relation Service Add

### PR DESCRIPTION
**Pull request by Youzi-nya**
要怎么分文件提pr

### CODE REVIEW

**Comment by Youzi-nya** [comment]
How do you split the file to pull requests？

**Comment by mo3et** [comment]
I think you only use different Commit to split, like #17 
And it is not PR, pls use issue.

**Comment by Youzi-nya** [comment]
thanks

**Review by Dyamidsteve — APPROVED** [review]
You seems to use personal method to Auth JWT.No Problem,you may change it later.

**Pull request closed without merging**
