### PR TITLE
feat: Makefile development tool

### PR DESCRIPTION
**Pull request by alilestera**
**What this PR does:**
Modify Makefiles

**Special notes for your reviewer:**
WIP, I'll remind you under this PR when it completed.

### CODE REVIEW

**Comment by mo3et** [comment]
I think you can refer to [beer-shop/app_makefile](https://github.com/go-kratos/beer-shop/blob/main/app_makefile)
They use import `include ../../../app_makefile` in `app/xxx/service/makefile`

**Comment by alilestera** [comment]
> I think you can refer to [beer-shop/app_makefile](https://github.com/go-kratos/beer-shop/blob/main/app_makefile) They use import `include ../../../app_makefile` in `app/xxx/service/makefile`

Thanks, but we don't need to create Makefile for every app. We can new a `make` target to boot a app. like 
```makefile
.PHONY: app-user
app-user:
    go run app/user/service/cmd/main.go -conf app/user/service/configs
```

**Comment by mo3et** [comment]
OK. Just a little reference. We also need to modify based on reality.

**Comment by Dyamidsteve** [comment]
I am also in favor of alilestera's approach. We can write a mkfile with boot commands for each app

**Review by Dyamidsteve — APPROVED** [review]
I'm not good at dealing with mkfile,but is it ok to make the commands a little more complex? For instance,tha command 'api' transfers to 'proto.gen.api'.Though it doesn't matter very much.

**Comment by alilestera** [comment]
> I'm not good at dealing with mkfile,but is it ok to make the commands a little more complex? For instance,tha command 'api' transfers to 'proto.gen.api'.Though it doesn't matter very much.

Do you mean that make public command literal more simple, for example, change `proto.api` to `api` ? Yes, that seems good because we all know that means api proto files.
But I want to divide these commands to more clear place. The prefix `proto` can be easily know the command is about proto files. So `app` is also.

**Pull request merged**
