### PR TITLE
feat: simplify code struct, create service example to help with developing

### PR DESCRIPTION
**Pull request by alilestera**
**What this PR does:**
Simplify code struct, delete some files that no need to use now. And create a service example, user service, to help with developing, the service has mock data.

**Special notes for your reviewer:**
Nothing.

### CODE REVIEW

**Comment by alilestera** [comment]
WIP, do not approve this PR.

**Comment by alilestera** [comment]
OK, I completed this work. This PR can be reviewed and approve if it's no problem now.

**Review by intyouss — APPROVED** [review]
LGTM,thank you.

**Review by Dyamidsteve — APPROVED** [review]
I approve this change.

**Review by intyouss — APPROVED** [review]
LGTM,thank you.

**Pull request merged**
