### PR TITLE
refactor: Look at the big picture and reprogram the catalog

### PR DESCRIPTION
**Pull request by intyouss**

### CODE REVIEW

**Comment by alilestera** [comment]
@intyouss Hi, is necessary to create `Dockerfile` and `Makefile` in every service directory?

**Review by mo3et — APPROVED** [review]
LGTM. Thanks for your contribution!

**Comment by intyouss** [comment]
> @intyouss Hi, is necessary to create `Dockerfile` and `Makefile` in every service directory?

Sorry, the app folder has not been rectified and needs to be cleaned🙂

**Review by alilestera — APPROVED** [review]
as a basic develop structure, it is ok.

**Pull request merged**
